version: '3'
 
services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "cd /myproject;python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
  redis:
    image: redis:alpine


